---
title: "AB Plots"
output:
  html_document:
    toc: true
---

```{r}
%md
This script uses the final models of antibiotics (week 1 and after week 1)
```

```{r}
library(sparklyr)

# create a sparklyr connection
sc <- spark_connect(method = "databricks")
```

```{r}
%scala
spark.sparkContext.hadoopConfiguration.set(
  "<directory>",
  "<key>"
)
```

```{r}
library(devtools)
```

```{r}
install_version("estimability", version = "1.4.1", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("lsmeans")
```

```{r}
dfFinalDataset <- spark_read_csv(sc,
                                 "//dfFinalDataset.csv",
                                 memory = FALSE,
                                 header = TRUE)

#for graphs:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
Palette2 <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
Palette3 <- c("#E69F00","#7ac9f5","#017858")
Palette4 <- c("#de8500","#83caf2","#006349") # suitable for color, black-white and color blindness
Palette5 <- c('#000000','#f58231',"#4363d8") # suitable for color, black-white and color blindness

#%scala
#spark.sparkContext.version
```

```{r}
# collect() executes the Spark query and returns the results to R

AnalysisData <- dfFinalDataset %>%
  dplyr::select(
    FarmIdentification, 
    Pen, 
    Flock, 
    VetId,
    Antibiotics,
    AntibioticsWeek1,
    AntibioticsAfterWeek1,
    NumberOfHouses,
    Type,
    Breed,
    Patio,
    OnFarmHatching,
    HatchYear,
    HatchQuarter,
    MeanAgeAtSlaughter,
    Thinning,
    EndFlockSize,
    PoultryFarmDensity,
    NumberOfFlockIDs
  ) %>%
  collect() %>%
  dplyr::filter(
    Type != "free range and organic",
    Patio == 0,
    NumberOfFlockIDs == 1
  ) %>%
  na.omit() %>%
  dplyr::mutate(
    Farm = factor(FarmIdentification),
    Pen = factor(Pen),
    Flock = factor(Flock),
    Vet = factor(VetId),
    Type = relevel(factor(Type), ref = "conventional"),
    FlockSizeGroup = cut(EndFlockSize, breaks = c(0, 18000, 29000, 100000), labels = c("<18000", "18000-29000", ">29000"), include.lowest = TRUE),
    NumberOfHousesGroup = cut(NumberOfHouses, breaks = c(0, 1.1, 2.1, 3.1, 100), labels = c("1", "2", "3", ">3"), include.lowest = TRUE),
    Year_Quarter = factor(paste0(HatchYear, "-", HatchQuarter)),
    HatchYear = factor(HatchYear),
    HatchQuarter = factor(HatchQuarter),
    logFlockSize = log2(EndFlockSize),
    EndFlockSize_scaled = scale(EndFlockSize),
    PoultryFarmDensity_scaled = scale(PoultryFarmDensity),
    Antibiotics = factor(Antibiotics)
  )

f_AnalysisData <- dfFinalDataset %>%
  dplyr::select(
    FarmIdentification, 
    Pen, 
    Flock, 
    VetId,
    Antibiotics,
    AntibioticsWeek1,
    NumberOfHouses,
    Type,
    Patio,
    OnFarmHatching,
    HatchYear,
    HatchQuarter,
    Thinning,
    EndFlockSize,
    PoultryFarmDensity
  ) %>%
  collect() %>%
  dplyr::filter(
    Type != "free range and organic",
    Patio == 0
  ) %>%
  na.omit() %>%
  dplyr::mutate(
    Farm = factor(FarmIdentification),
    Pen = factor(Pen),
    Flock = factor(Flock),
    Vet = factor(VetId),
    Type = relevel(factor(Type), ref = "conventional"),
    NumberOfHousesGroup = cut(NumberOfHouses, breaks = c(0, 1.1, 2.1, 3.1, 100), labels = c("1", "2", "3", ">3"), include.lowest = TRUE),
    HatchYear = factor(HatchYear),
    HatchQuarter = factor(HatchQuarter),
    logFlockSize = log2(EndFlockSize),
    EndFlockSize_scaled = scale(EndFlockSize),
    PoultryFarmDensity_scaled = scale(PoultryFarmDensity),
    AntibioticsWeek1 = factor(AntibioticsWeek1)
  )
```

```{r}
%md
#Descriptive
```

```{r}
#+++++++++++++++++++++++++
# Function to calculate the mean and the standard deviation (FOR PROPORTION!)
  # for each group
#+++++++++++++++++++++++++
# data : a data frame
# varname : the name of a column containing the variable
  #to be summariezed
# groupnames : vector of column names to be used as
  # grouping variables
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sqrt(mean(x[[col]], na.rm=TRUE)*(1-mean(x[[col]], na.rm=TRUE))/length(x[[col]]))
      )
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

Abwk1_sum <- data_summary(AnalysisData, varname="AntibioticsWeek1", 
                    groupnames=c("Type", "HatchYear"))
AbAfterwk1_sum <- data_summary(AnalysisData, varname="AntibioticsAfterWeek1", 
                    groupnames=c("Type", "HatchYear"))                    
```

```{r}
plot1 <- Abwk1_sum %>%
    ggplot2::ggplot(ggplot2::aes(x = factor(HatchYear), y = AntibioticsWeek1, group = Type, color = Type)) +
    ggplot2::geom_line(size = 1) +
    ggplot2::geom_point(
      ggplot2::aes(shape = Type),
      size = 3) +
    ggplot2::geom_errorbar(
      ggplot2::aes(ymin=AntibioticsWeek1-sd, ymax=AntibioticsWeek1+sd), 
      width=.5) +
    # total of all types:
    ggplot2::stat_summary(
      data = AnalysisData,
      ggplot2::aes(x = factor(HatchYear), y = AntibioticsWeek1, group = 1),
      geom = "line", 
      fun = "mean", 
      size = 1, 
      linetype = 2
    ) +  
    ggplot2::labs(
        title = "A",
        x = "Year", 
        y="Treated with antibiotics in first week"
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      axis.title.x = ggplot2::element_text(size = 0),
      axis.text= ggplot2::element_text(size=15),
      axis.title.y = ggplot2::element_text(size = 15),
      legend.title = ggplot2::element_text(size=0),
      legend.text = ggplot2::element_text(size=12),
      legend.position = c(0.2, 0.8),
      axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
      plot.title = ggplot2::element_text(size = 15, hjust = 0.5),
      plot.margin = ggplot2::unit(c(0,0.5,0,0),"cm")
    ) +
    ggplot2::scale_y_continuous(labels = scales::percent) +
    ggplot2::coord_cartesian(ylim=c(0, 0.3)) +
    ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
    ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
plot2 <- AbAfterwk1_sum %>%
    ggplot2::ggplot(ggplot2::aes(x = factor(HatchYear), y = AntibioticsAfterWeek1, group = Type, color = Type)) +
    ggplot2::geom_line(
      size = 1,
      show.legend = FALSE #werkt niet?
    ) +
    ggplot2::geom_point(
      ggplot2::aes(shape = Type),
      size = 3) +
    ggplot2::geom_errorbar(
      ggplot2::aes(ymin=AntibioticsAfterWeek1-sd, ymax=AntibioticsAfterWeek1+sd, color = Type), 
      width=.5
    ) +
    ggplot2::stat_summary(
      data = AnalysisData, 
      ggplot2::aes(x = factor(HatchYear), y = AntibioticsAfterWeek1, group = 1), 
      geom = "line", 
      fun = "mean", 
      size = 1, 
      linetype = 2) +  
    ggplot2::labs(
        title = "B",
        x = "Year", 
        y="Treated with antibiotics after first week"
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(size = 15, hjust = 0.5),
      axis.title.x = ggplot2::element_text(size = 0),
      axis.text= ggplot2::element_text(size= 15),,
      axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
      axis.title.y = ggplot2::element_text(size = 15),
      legend.title = ggplot2::element_text(size=0),
      legend.text = ggplot2::element_text(size=12),
      legend.position = "none",
      plot.margin = ggplot2::unit(c(t = 0, r = 0, b = 0, l = 0.5),"cm")
    ) +
    ggplot2::ylim(0, 0.3) +
    ggplot2::scale_y_continuous(
      labels = scales::percent
    ) +
    ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
    ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
gridExtra::grid.arrange(plot1, plot2, ncol = 2, respect = TRUE)
```

```{r}
plot2_r <- AbAfterwk1_sum %>%
    ggplot2::ggplot(ggplot2::aes(x = factor(HatchYear), y = AntibioticsAfterWeek1, group = Type, color = Type)) +
    ggplot2::geom_line(size = 1, show.legend = FALSE) +
    ggplot2::geom_point(
      ggplot2::aes(shape = Type),
      size = 3) +
    ggplot2::geom_ribbon(
      ggplot2::aes(ymin=AntibioticsAfterWeek1-sd, ymax=AntibioticsAfterWeek1+sd, fill = Type), 
      alpha = .2, 
      color = NA,
      show.legend = FALSE
    ) +
    ggplot2::stat_summary(data = AnalysisData, ggplot2::aes(x = factor(HatchYear), y = AntibioticsAfterWeek1, group = 1), geom = "line", fun = "mean", size = 1, linetype = 2) +  
    ggplot2::labs(
        title = "B",
        x = "Year", 
        y="Treated with antibiotics after first week"
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(size = 15,  hjust = 0.5),
      axis.title.x = ggplot2::element_text(size = 0),
      axis.text= ggplot2::element_text(size=15),
      axis.title.y = ggplot2::element_text(size = 15),
      legend.title = ggplot2::element_text(size=0),
      legend.text = ggplot2::element_text(size=12),
      legend.position = "none",
      axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
      plot.margin = ggplot2::unit(c(t = 0, r = 0, b = 0, l = 0.5),"cm")
    ) +
    ggplot2::scale_y_continuous(labels = scales::percent) +
    ggplot2::coord_cartesian(ylim=c(0, 0.3)) +
    ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
    ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW'))  +
    ggplot2::scale_fill_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
plot1_r <- Abwk1_sum %>%
    ggplot2::ggplot(ggplot2::aes(x = factor(HatchYear), y = AntibioticsWeek1, group = Type, color = Type)) +
    ggplot2::geom_line(
      size = 1
    ) +
    ggplot2::geom_point(
      ggplot2::aes(shape = Type),
      size = 3) +
    ggplot2::geom_ribbon(
      ggplot2::aes(ymin=AntibioticsWeek1-sd, ymax=AntibioticsWeek1+sd, fill = Type), 
      alpha = .2, 
      color = NA,
      show.legend = FALSE
    ) +
    # total of all types:
    ggplot2::stat_summary(
      data = AnalysisData,
      ggplot2::aes(x = factor(HatchYear), y = AntibioticsWeek1, group = 1),
      geom = "line", 
      fun = "mean", 
      size = 1, 
      linetype = 2
    ) +  
    ggplot2::labs(
        title = "A",
        x = "Year", 
        y="Treated with antibiotics in first week"
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(size = 15,  hjust = 0.5),
      axis.title.x = ggplot2::element_text(size = 0),
      axis.text= ggplot2::element_text(size=15),
      axis.title.y = ggplot2::element_text(size = 15),
      legend.title = ggplot2::element_text(size=0),
      legend.text = ggplot2::element_text(size=12),
      legend.position = c(0.2, 0.8),
      axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
      plot.margin = ggplot2::unit(c(t = 0, r = 0.5, b = 0, l = 0),"cm")
    ) +
    ggplot2::scale_y_continuous(labels = scales::percent) +
    ggplot2::coord_cartesian(ylim=c(0, 0.3)) +
    ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
    ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW'))   +
    ggplot2::scale_fill_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
gridExtra::grid.arrange(plot1_r, plot2_r, ncol = 2, respect = TRUE)
```

```{r}
%md
#Model
```

```{r}
dbutils.fs.cp ("dbfs:/tmp/model3_1_2.rda", paste("file:", getwd(), sep=""))
```

```{r}
load(file = paste(getwd(),"/model3_1_2.rda", sep=""))
```

```{r}
dbutils.fs.cp ("dbfs:/tmp/f_model_new.rda", paste("file:", getwd(), sep=""))
```

```{r}
load(file = paste(getwd(),"/f_model_new.rda", sep=""))
```

```{r}
ABAfterWk1Model = model3_1_2
ABWk1Model = f_model_new
```

```{r}
f_ls_type = lsmeans::lsmeans(ABWk1Model, ~ Type | HatchYear)

f_ls_type_cld <- multcomp::cld(object = f_ls_type,
                       adjust = "Tukey",
                       Letters = letters,
                       alpha = 0.05,
                       type = "response",
                       decreasing = TRUE)
```

```{r}
pointsize = 3
linesize = 1
lettersize = 4

plot3 <- f_ls_type_cld %>%
  ggplot2::ggplot(
    ggplot2::aes(x = factor(HatchYear), y = prob, group = Type, color = Type)
  ) +
  ggplot2::geom_line(
    linewidth = linesize
  ) +  
  ggplot2::geom_point(
    ggplot2::aes(shape = Type),
    size = pointsize
  ) +  
  ggplot2::geom_errorbar(
    ggplot2::aes(ymin=asymp.LCL, ymax=asymp.UCL), 
    width=.7,
    position = ggplot2::position_dodge(0.1)
  ) +
  ggplot2::geom_text(
    data=f_ls_type_cld[f_ls_type_cld$Type=='conventional',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1),
    position = ggplot2::position_nudge(x = 0.2),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=f_ls_type_cld[f_ls_type_cld$Type=='medium',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1.5),
    position = ggplot2::position_nudge(x = 0.3),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=f_ls_type_cld[f_ls_type_cld$Type=='slow-growing',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = 1.7),
    position = ggplot2::position_nudge(x = 0.3),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::labs(
      title = "A",
      y="Probability of treatment in first week"
  ) +
  ggplot2::theme_classic() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5, size = 15),
    axis.title.x = ggplot2::element_text(size = 0),
    axis.text= ggplot2::element_text(size=15),
    axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
    axis.title.y = ggplot2::element_text(size = 15),
    legend.title = ggplot2::element_text(size=0),
    legend.text = ggplot2::element_text(size=12),
    legend.position = c(0.2, 0.8),
    plot.margin = ggplot2::unit(c(t = 0, r = 0.5, b = 0, l = 0),"cm")
  ) +
  ggplot2::scale_y_continuous(
    labels = scales::percent,
    limits = c(0,0.25)
    ) +
  ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
  ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
ls_type = lsmeans::lsmeans(ABAfterWk1Model, ~ Type | HatchYear)

ls_type_cld <- multcomp::cld(object = ls_type,
                       adjust = "Tukey",
                       Letters = letters,
                       alpha = 0.05,
                       type = "response",
                       decreasing = TRUE)
```

```{r}
pointsize = 3
linesize = 1
lettersize = 4

plot4 <- ls_type_cld %>%
  ggplot2::ggplot(
    ggplot2::aes(x = factor(HatchYear), y = prob, group = Type, color = Type)
  ) +
  ggplot2::geom_line(
    linewidth = linesize
  ) +  
  ggplot2::geom_point(
    ggplot2::aes(shape = Type),
    size = pointsize
  ) +  
  ggplot2::geom_errorbar(
    ggplot2::aes(ymin=asymp.LCL, ymax=asymp.UCL), 
    width=.7,
    position = ggplot2::position_dodge(0.1)
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[ls_type_cld$Type=='conventional',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1),
    position = ggplot2::position_nudge(x = 0.2),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[ls_type_cld$Type=='medium',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1.5),
    position = ggplot2::position_nudge(x = 0.3),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[ls_type_cld$Type=='slow-growing',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = 1.7),
    position = ggplot2::position_nudge(x = 0.3),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::labs(
      title = "B",
      y="Probability of treatment after first week"
  ) +
  ggplot2::theme_classic() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5, size = 15),
    axis.title.x = ggplot2::element_text(size = 0),
    axis.text= ggplot2::element_text(size=15),
    axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
    axis.title.y = ggplot2::element_text(size = 15),
    legend.title = ggplot2::element_text(size=0),
    legend.text = ggplot2::element_text(size=12),
    legend.position = "none",
    legend.key.width= ggplot2::unit(0,"pt"),
    plot.margin = ggplot2::unit(c(t = 0, r = 0, b = 0, l = 0.5),"cm")
  ) +
  ggplot2::scale_y_continuous(
    labels = scales::percent,
    limits = c(0,0.25)
    ) +
  ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
  ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
gridExtra::grid.arrange(plot3, plot4, ncol = 2, respect = TRUE)
```

```{r}
pointsize = 3
linesize = 1
lettersize = 4

plot3_r <- f_ls_type_cld %>%
  ggplot2::ggplot(
    ggplot2::aes(x = factor(HatchYear), y = prob, group = Type, color = Type)
  ) +
  ggplot2::geom_line(
    linewidth = linesize
  ) +  
  ggplot2::geom_point(
    ggplot2::aes(shape = Type),
    size = pointsize
  ) +  
  ggplot2::geom_ribbon(
    ggplot2::aes(ymin=asymp.LCL, ymax=asymp.UCL, fill = Type), 
    alpha = 0.2,
    color = NA,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=f_ls_type_cld[f_ls_type_cld$Type=='conventional',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=f_ls_type_cld[(f_ls_type_cld$Type=='medium'& ls_type_cld$HatchYear!='2013'),],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1.1),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[(ls_type_cld$Type=='medium' & ls_type_cld$HatchYear=='2013'),],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = 2.8),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=f_ls_type_cld[f_ls_type_cld$Type=='slow-growing' & ls_type_cld$HatchYear!='2013',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = 1.5),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[ls_type_cld$Type=='slow-growing' & ls_type_cld$HatchYear=='2013',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1.9),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::labs(
      title = "A",
      y="Probability of treatment in first week"
  ) +
  ggplot2::theme_classic() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5, size = 15),
    axis.title.x = ggplot2::element_text(size = 0),
    axis.text= ggplot2::element_text(size=15),
    axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
    axis.title.y = ggplot2::element_text(size = 15),
    legend.title = ggplot2::element_text(size=0),
    legend.text = ggplot2::element_text(size=12),
    legend.position = c(0.2, 0.8),
    plot.margin = ggplot2::unit(c(t = 0, r = 0.5, b = 0, l = 0),"cm")
  ) +
  ggplot2::scale_y_continuous(
    labels = scales::percent,
    limits = c(0,0.25)
    ) +
  ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
  ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW')) +
  ggplot2::scale_fill_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
pointsize = 3
linesize = 1
lettersize = 4

plot4_r <- ls_type_cld %>%
  ggplot2::ggplot(
    ggplot2::aes(x = factor(HatchYear), y = prob, group = Type, color = Type)
  ) +
  ggplot2::geom_line(
    linewidth = linesize
  ) +  
  ggplot2::geom_point(
    ggplot2::aes(shape = Type),
    size = pointsize
  ) +  
  ggplot2::geom_ribbon(
    ggplot2::aes(ymin=asymp.LCL, ymax=asymp.UCL, fill = Type), 
    alpha = 0.2,
    color = NA,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[ls_type_cld$Type=='conventional',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[ls_type_cld$Type=='medium',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = -1),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::geom_text(
    data=ls_type_cld[ls_type_cld$Type=='slow-growing',],
    ggplot2::aes(label = gsub(" ", "", .group), vjust = 1.7),
    position = ggplot2::position_nudge(x = 0),  
    size = lettersize,
    show.legend = FALSE
  ) +
  ggplot2::labs(
      title = "B",
      y="Probability of treatment after first week"
  ) +
  ggplot2::theme_classic() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5, size = 15),
    axis.title.x = ggplot2::element_text(size = 0),
    axis.text= ggplot2::element_text(size=15),
    axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1),
    axis.title.y = ggplot2::element_text(size = 15),
    legend.title = ggplot2::element_text(size=0),
    legend.text = ggplot2::element_text(size=12),
    legend.position = "none",
    legend.key.width= ggplot2::unit(0,"pt"),
    plot.margin = ggplot2::unit(c(t = 0, r = 0, b = 0, l = 0.5),"cm")
  ) +
  ggplot2::scale_y_continuous(
    labels = scales::percent,
    limits = c(0,0.25)
    ) +
  ggplot2::scale_color_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW')) +
  ggplot2::scale_shape_manual(values = c(16,15,17), labels=c('CONV', 'MED', 'SLOW')) +
  ggplot2::scale_fill_manual(values=Palette5, labels=c('CONV', 'MED', 'SLOW'))
```

```{r}
gridExtra::grid.arrange(plot3_r, plot4_r, ncol = 2, respect = TRUE)
```
