
---
title: "Analysis Slow-growing - AB"
output:
  html_document:
    toc: true
---


```{r}
library(sparklyr)

# create a sparklyr connection
sc <- spark_connect(method = "databricks")
```


```{r}
%scala
spark.sparkContext.hadoopConfiguration.set(
  "<directory>",
  "<key>"
)
```


```{r}
dfFinalDataset <- spark_read_csv(sc,
                                 "//dfFinalDataset.csv",
                                 memory = FALSE,
                                 header = TRUE)

#for graphs:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
Palette2 <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
Palette3 <- c("#E69F00","#7ac9f5","#017858")
Palette4 <- c("#de8500","#83caf2","#006349") # suitable for color, black-white and color blindness
Palette5 <- c('#000000','#f58231',"#4363d8") # suitable for color, black-white and color blindness

#%scala
#spark.sparkContext.version
```


```{r}
# collect() executes the Spark query and returns the results to R

AnalysisData <- dfFinalDataset %>%
  dplyr::select(
    FarmIdentification, 
    Pen, 
    Flock, 
    VetId,
    Antibiotics,
    AntibioticsWeek1,
    AntibioticsAfterWeek1,
    NumberOfHouses,
    Type,
    Breed,
    Patio,
    OnFarmHatching,
    HatchYear,
    HatchQuarter,
    MeanAgeAtSlaughter,
    Thinning,
    EndFlockSize,
    PoultryFarmDensity,
    NumberOfFlockIDs
  ) %>%
  collect() %>%
  dplyr::filter(
    Type != "free range and organic",
    Patio == 0,
    NumberOfFlockIDs == 1
  ) %>%
  na.omit() %>%
  dplyr::mutate(
    Farm = factor(FarmIdentification),
    Pen = factor(Pen),
    Flock = factor(Flock),
    Vet = factor(VetId),
    Type = relevel(factor(Type), ref = "conventional"),
    FlockSizeGroup = cut(EndFlockSize, breaks = c(0, 18000, 29000, 100000), labels = c("<18000", "18000-29000", ">29000"), include.lowest = TRUE),
    NumberOfHousesGroup = cut(NumberOfHouses, breaks = c(0, 1.1, 2.1, 3.1, 100), labels = c("1", "2", "3", ">3"), include.lowest = TRUE),
    Year_Quarter = factor(paste0(HatchYear, "-", HatchQuarter)),
    HatchYear = factor(HatchYear),
    HatchQuarter = factor(HatchQuarter),
    logFlockSize = log2(EndFlockSize),
    EndFlockSize_scaled = scale(EndFlockSize),
    PoultryFarmDensity_scaled = scale(PoultryFarmDensity),
    Antibiotics = factor(Antibiotics)
  )
```


```{r}
%md
## Descriptive Statistics
```


```{r}
table(AnalysisData$Type, AnalysisData$HatchYear)
```


```{r}
prop.table(table(AnalysisData$Type, AnalysisData$HatchYear), m=2)
```


```{r}
prop.table(table(AnalysisData$Type, AnalysisData$Antibiotics), m=1)
```


```{r}
prop.table(table(AnalysisData$Type, AnalysisData$Thinning), m=1)
```


```{r}
summary(AnalysisData)
```


```{r}
d = AnalysisData %>% 
  dplyr::group_by(FarmIdentification, HatchYear) %>% 
  dplyr::summarise(houses = mean(NumberOfHouses))

summary(d$houses)
```


```{r}
Slow = AnalysisData %>% dplyr::filter(Type == 'slow-growing')
Med = AnalysisData %>% dplyr::filter(Type == 'medium')
Conv = AnalysisData %>% dplyr::filter(Type == 'conventional')
```


```{r}
farms = AnalysisData %>% dplyr::group_by(FarmIdentification, Type) %>% dplyr::summarize(n = dplyr::n())
farms %>% dplyr::group_by(Type) %>% dplyr::summarize(n = dplyr::n())
```


```{r}
AnalysisData %>%
  dplyr::group_by(Type) %>%
  dplyr::summarise(Q1 = quantile(EndFlockSize, prob=c(.25)),
                   median = quantile(EndFlockSize, prob=c(.5)),
                   Q3 = quantile(EndFlockSize, prob=c(.75)))
```


```{r}
AnalysisData %>%
  dplyr::group_by(Type) %>%
  dplyr::summarise(min = min(MeanAgeAtSlaughter),
                   Q1 = quantile(MeanAgeAtSlaughter, prob=c(.25)),
                   median = quantile(MeanAgeAtSlaughter, prob=c(.5)),
                   Q3 = quantile(MeanAgeAtSlaughter, prob=c(.75)),
                   max = max(MeanAgeAtSlaughter))
```


```{r}
par(mfrow = c(3,3))
hist(Conv$MeanAgeAtSlaughter)
hist(Med$MeanAgeAtSlaughter)
hist(Slow$MeanAgeAtSlaughter)
hist(Conv$EndFlockSize)
hist(Med$EndFlockSize)
hist(Slow$EndFlockSize)
```


```{r}
AnalysisData %>%
  dplyr::group_by(Type) %>%
  dplyr::summarise(Q1 = quantile(PoultryFarmDensity, prob=c(.25)),
                   median = quantile(PoultryFarmDensity, prob=c(.5)),
                   Q3 = quantile(PoultryFarmDensity, prob=c(.75)))
```


```{r}
AnalysisData %>%
  dplyr::group_by(Type) %>%
  dplyr::summarise(Q1 = quantile(NumberOfHouses, prob=c(.25)),
                   median = quantile(NumberOfHouses, prob=c(.5)),
                   Q3 = quantile(NumberOfHouses, prob=c(.75)))
```


```{r}
%md
## Preliminary Analyses
```


```{r}
NumVar <- AnalysisData %>%
  select(        
    'PoultryFarmDensity',
    'NumberOfHouses',
    'EndFlockSize',
  )

round(cor(NumVar),2)
```


```{r}
prop.table(table(AnalysisData$HatchYear, AnalysisData$Type), margin = 1)
```


```{r}
par(mfrow=c(3,3))

boxplot(AnalysisData$PoultryFarmDensity ~ AnalysisData$Type)
boxplot(AnalysisData$EndFlockSize ~ AnalysisData$Type)
boxplot(AnalysisData$NumberOfHouses ~ AnalysisData$Type)

boxplot(AnalysisData$PoultryFarmDensity ~ AnalysisData$Thinning)
boxplot(AnalysisData$EndFlockSize ~ AnalysisData$Thinning)
boxplot(AnalysisData$NumberOfHouses ~ AnalysisData$Thinning)

boxplot(AnalysisData$PoultryFarmDensity ~ AnalysisData$HatchQuarter)
boxplot(AnalysisData$EndFlockSize ~ AnalysisData$HatchQuarter)
boxplot(AnalysisData$NumberOfHouses ~ AnalysisData$HatchQuarter)
```


```{r}
%md
# Antibiotics after week 1
```


```{r}
%md
## Univariate models
```


```{r}
model0.1 = lme4::glmer(AntibioticsAfterWeek1 ~ 1 + (1|Farm) + (1|Vet), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",  #bobyqa should be the default optimiser
                              optCtrl=list(maxfun=100000)))

AIC(model0.1)
```


```{r}
model1.1 = lme4::glmer(AntibioticsAfterWeek1 ~ Type + (1|Farm) + (1|Vet), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))

AIC(model1.1)
```


```{r}
ls = lsmeans::lsmeans(model1.1, revpairwise ~ Type, type = "response")
summary(ls, infer = TRUE)$contrasts
```


```{r}
model1_2 = lme4::glmer(AntibioticsAfterWeek1 ~ EndFlockSize_scaled + (1|Farm) + (1|VetId), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))

model1_3 = lme4::glmer(AntibioticsAfterWeek1 ~ logFlockSize + (1|Farm) + (1|VetId), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))
```


```{r}
anova(model1_2, model1_3)
```


```{r}
%md
## Backwards stepwise selection
```


```{r}
model2_1 = lme4::glmer(AntibioticsAfterWeek1 ~ 
                       logFlockSize + 
                       NumberOfHousesGroup +
                       HatchYear +
                       HatchQuarter +
                       Type + 
                       Thinning +
                       PoultryFarmDensity_scaled +
                       (1|Farm) + (1|Vet), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))

drop1(model2_1, test = "Chisq")
```


```{r}
model2_2 = lme4::glmer(AntibioticsAfterWeek1 ~ 
                       logFlockSize + 
                       NumberOfHousesGroup +
                       HatchYear +
                       HatchQuarter +
                       Type + 
                       Thinning +
                       (1|Farm) + (1|Vet), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))
```


```{r}
drop1(model2_2, test = "Chisq")
```


```{r}
model2_3 = lme4::glmer(AntibioticsAfterWeek1 ~ 
                       logFlockSize + 
                       NumberOfHousesGroup +
                       HatchYear +
                       HatchQuarter +
                       Type + 
                       (1|Farm) + (1|Vet), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))

drop1(model2_3, test = "Chisq")
```


```{r}
ss <- lme4::getME(model2_3,c("theta","fixef"))
model2_3 <- update(model2_3,start=ss)
```


```{r}
save(model2_3, file = "model2_3.rda")
```


```{r}
dbutils.fs.cp (paste("file:", getwd(),"/model2_3.rda", sep=""), "dbfs:/tmp")
```


```{r}
model_conv = lme4::glmer(AntibioticsAfterWeek1 ~ 
                       logFlockSize + 
                       NumberOfHousesGroup +
                       HatchYear +
                       HatchQuarter +
                       Thinning +
                       (1|Farm) + (1|Vet), 
  data = Conv,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))
```


```{r}
summary(model_conv)
```


```{r}
%md
## Test interactions
```


```{r}
model3_1 = lme4::glmer(AntibioticsAfterWeek1 ~ 
                       logFlockSize + 
                       HatchYear +
                       HatchQuarter +
                       Type + 
                       NumberOfHousesGroup +
                       Type * HatchYear +
                       (1|Farm) + (1|Vet), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))

AIC(model3_1)
```


```{r}
ss <- lme4::getME(model3_1,c("theta","fixef"))
model3_1 <- update(model3_1,start=ss,control=lme4::glmerControl(optCtrl=list(ftol_abs=1e-8,xtol_abs=1e-8)))
```


```{r}
model3_1_2 <- model3_1
```


```{r}
save(model3_1_2, file = "model3_1_2.rda")
```


```{r}
dbutils.fs.cp (paste("file:", getwd(),"/model3_1_2.rda", sep=""), "dbfs:/tmp")
```


```{r}
dbutils.fs.cp ("dbfs:/tmp/model3_1.rda", paste("file:", getwd(), sep=""))
```


```{r}
load(file = paste(getwd(),"/model3_1_2.rda", sep=""))
```


```{r}
AIC(model3_1_2)
```


```{r}
model3_2 = lme4::glmer(AntibioticsAfterWeek1 ~ 
                       logFlockSize + 
                       HatchYear +
                       HatchQuarter +
                       Type + 
                       Thinning +
                       Type * logFlockSize +
                       (1|Farm) + (1|Vet), 
  data = AnalysisData,
  family = binomial,
  control= lme4::glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000)))

AIC(model3_2)
```


```{r}
ss <- lme4::getME(model3_2,c("theta","fixef"))
model3_2 <- update(model3_2,start=ss,control=lme4::glmerControl(optCtrl=list(ftol_abs=1e-8,xtol_abs=1e-8)))
```


```{r}
AIC(model3_2)
```


```{r}
%md
## Results
```


```{r}
dbutils.fs.cp ("dbfs:/tmp/model3_1_2.rda", paste("file:", getwd(), sep=""))
```


```{r}
load(file = paste(getwd(),"/model3_1_2.rda", sep=""))
```


```{r}
FinalModel = model3_1_2
```


```{r}
performance::check_collinearity(FinalModel)
```


```{r}
summary(FinalModel)
```


```{r}
cbind(round(exp(summary(model3_1)$coefficients[-1, 1]), 2), round(exp(confint(model3_1, method = "Wald"))[-(1:3),],2))
```


```{r}
ls_type = lsmeans::lsmeans(FinalModel, trt.vs.ctrl ~ HatchYear, type = "response")
summary(ls_type, infer = TRUE)$contrasts
```


```{r}
ls_type = lsmeans::lsmeans(FinalModel, revpairwise ~ Type|HatchYear, type = "response")
summary(ls_type, infer = TRUE)$contrasts
```


```{r}
ls = lsmeans::lsmeans(FinalModel, revpairwise ~ HatchQuarter, type = "response")
summary(ls, infer = TRUE)$contrasts
```


```{r}
ls_house = lsmeans::lsmeans(FinalModel, revpairwise ~ NumberOfHousesGroup, type = "response")
summary(ls_house, infer = TRUE)$contrasts
```


```{r}
lsmeans_house <- lsmeans::lsmeans(FinalModel, revpairwise ~ NumberOfHousesGroup, infer = TRUE)

house_sum <- summary(lsmeans_house, type = "response")[[1]]   # results are on response scale: probs, se, LCL, UCL

plotHouse <- house_sum %>%
  ggplot2::ggplot(ggplot2::aes(x = factor(NumberOfHousesGroup), y = prob)) +
  ggplot2::geom_bar(
    stat="identity",
    position = "dodge",
    fill = "#0D4678",
    alpha = 0.7
  ) +  
  ggplot2::geom_errorbar(
    ggplot2::aes(ymin=asymp.LCL, ymax=asymp.UCL), 
    width=.3, 
    position = ggplot2::position_dodge(.9)
  ) +
  ggplot2::labs(
      y="Probability of treatment after wk1",
      x="Number of houses"
  ) +
  ggplot2::theme_classic() +
  ggplot2::scale_y_continuous(limits = c(0, 0.08), labels = scales::percent_format(accuracy = 1)) +
  ggplot2::theme(
      axis.title.x = ggplot2::element_text(size = 15),
      axis.text= ggplot2::element_text(size=15),
      axis.title.y = ggplot2::element_text(size = 15)
  )

  gridExtra::grid.arrange(plotHouse, ncol = 2, respect = TRUE)
```


```{r}
ls = lsmeans::lsmeans(FinalModel, revpairwise ~ Type, type = "response")
summary(ls, infer = TRUE)$contrasts
```


```{r}
eff <- as.data.frame(lsmeans::lsmeans(
  FinalModel, ~ logFlockSize, rg.limit = 1000000,
  at = list(logFlockSize = seq(4.3, 16.3, 0.5))
))

# own addition:
# change EndFlockSizes to unscaled EndFlockSize, and retain the rest of the dataframe (odds and SE)
eff$EndFlockSize <- 2^(eff$logFlockSize)

# we get estimated marginal means on link-scale, 
# so get link-inverse function to back-transform to probabilities
linv <- insight::link_inverse(FinalModel)
eff$lsmean <- linv(eff$lsmean)
eff$asymp.LCL <- linv(eff$asymp.LCL)
eff$asymp.UCL <- linv(eff$asymp.UCL)

plotFlockSize <- ggplot2::ggplot(eff, ggplot2::aes(x = EndFlockSize/1000, y = lsmean)) + 
  ggplot2::geom_ribbon(
    ggplot2::aes(ymin = asymp.LCL, ymax = asymp.UCL),
    alpha = .1,
    fill = "#0D4678"
  ) +
  ggplot2::geom_line(size = 2, color = "#0D4678") +
  ggplot2::theme_classic() +
  ggplot2::labs(
      x = "Flock Size (x1000)",
      y="Probability of treatment after wk1"
  ) +
  ggplot2::scale_y_continuous(limits = c(0, 0.15), labels = scales::percent) +
  ggplot2::theme(
    text = ggplot2::element_text(size = 21),
    axis.title.x = ggplot2::element_text(
      size = 15,
      margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0)
    ),
    axis.title.y = ggplot2::element_text(
      size = 15,
      margin = ggplot2::margin(t = 0, r = 20, b = 0, l = 0)
    )
  )
```


```{r}
lsmeans_ab <- lsmeans::lsmeans(FinalModel, revpairwise ~ HatchQuarter, infer = TRUE)

p_values <- summary(lsmeans_ab$contrasts)$p.value
group_labels <- summary(lsmeans_ab$contrasts)$contrast
alpha <- 0.05

# Identify significant comparisons based on p-values
significant_comparisons <- group_labels[p_values < alpha]

ab_sum <- summary(lsmeans_ab, type = "response")[[1]]   # results are on response scale: probs, se, LCL, UCL

plotQuarter <- ab_sum %>%
  ggplot2::ggplot(ggplot2::aes(x = factor(HatchQuarter), y = prob)) +
  ggplot2::geom_bar(
    stat="identity",
    position = "dodge",
    fill = "#0D4678",
    alpha = 0.7
  ) +  
  ggplot2::geom_errorbar(
    ggplot2::aes(ymin=asymp.LCL, ymax=asymp.UCL), 
    width=.3, 
    position = ggplot2::position_dodge(.9)
  ) +
  ggplot2::labs(
      y="Probability of treatment after wk1",
      x="Quarter of hatch"
  ) +
  ggplot2::theme_classic() +
  ggplot2::scale_y_continuous(limits = c(0, 0.08), labels = scales::percent_format(accuracy = 1)) +
  ggplot2::theme(
      axis.title.x = ggplot2::element_text(size = 15),
      axis.text= ggplot2::element_text(size=15),
      axis.title.y = ggplot2::element_text(size = 15)
  )

  gridExtra::grid.arrange(plotFlockSize, plotQuarter, ncol = 2, respect = TRUE)
```

